<?php
// $Id$

/**
 * @file
 * Annihilate smurfs module - allows authorised users to override the "blue smurf" text returned by the search module.
 */

// constants
define('ANNIHILATE_TERM_1', 'blue');
define('ANNIHILATE_TERM_2', 'smurf');


/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function annihilatesmurfs_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#annihilatesmurfs":
      $output = check_markup(file_get_contents( dirname(__FILE__) ."/README.txt") );
      break;
  }
  return $output;
}



/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the annihilatesmurfs module
 */
function annihilatesmurfs_perm() {
  return array('administer annihilatesmurfs');
}



/**
 * Rewrite the search results box
 *
 * Override theme_box and rewrite the example search terms
 * @ingroup themeable
 */
function phptemplate_box($title, $content, $region = 'main') {
  if ($title == 'Your search yielded no results') {
    // update string
	$content = annihilatesmurfs_custom_search_text($content);
  }
  $output = '<h2 class="title">'. $title .'</h2><div>'. $content .'</div>';
  return $output;
}



/**
 * Return custom search text
 */
function annihilatesmurfs_custom_search_text($content) {
  // get replacement text (if any)
  $term1 = variable_get('annihilatesmurfs_term1', ANNIHILATE_TERM_1);
  $term2 = variable_get('annihilatesmurfs_term2', ANNIHILATE_TERM_2);
  
  // to preserve translatability, need to just replace the search terms
  $content = preg_replace('/'. ANNIHILATE_TERM_1 .'/', $term1, $content);
  $content = preg_replace('/'. ANNIHILATE_TERM_2 .'/', $term2, $content);
  
  return $content;
}


/**
 * Implement administration form
 */
function annihilatesmurfs_admin() {

  $form['annihilatesmurfs_intro'] = array(
    '#value' => t('Replace the "@term1 @term2" text with whatever you like.', array('@term1' => ANNIHILATE_TERM_1, '@term2' => ANNIHILATE_TERM_2)) .'<br />'.  l('Get help on the Annihilate smurfs module here', 'admin/help/annihilatesmurfs'),
  );
  $form['annihilatesmurfs_term1'] = array(
    '#type' => 'textfield',
    '#title' => t('First term'),
    '#default_value' => variable_get('annihilatesmurfs_term1', ANNIHILATE_TERM_1),
    '#size' => 20,
    '#maxlength' => 50,
    '#description' => t('The first example search term (default value: "@term1").', array('@term1' => ANNIHILATE_TERM_1)),
    '#required' => FALSE,
  );
  $form['annihilatesmurfs_term2'] = array(
    '#type' => 'textfield',
    '#title' => t('Second term'),
    '#default_value' => variable_get('annihilatesmurfs_term2', ANNIHILATE_TERM_2),
    '#size' => 20,
    '#maxlength' => 50,
    '#description' => t('The second example search term (default value: "@term2").', array('@term2' => ANNIHILATE_TERM_1)),
    '#required' => FALSE,
  );
  // add live preview placeholder - see annihilatesmurfs.js for functionality
  $live_placeholder_text = annihilatesmurfs_custom_search_text(t('<ul>
<li>Check if your spelling is correct.</li>
<li>Remove quotes around phrases to match each word individually: <em>"blue smurf"</em> will match less than <em>blue smurf</em>.</li>
<li>Consider loosening your query with <em>OR</em>: <em>blue smurf</em> will match less than <em>blue OR smurf</em>.</li>
</ul>'));
  $form['annihilatesmurfs_live_preview'] = array(
    '#value' => '<div id="annihilatesmurfs-live-preview"><h3>Preview</h3><div style="border:1px solid #ccc; padding:5px; margin:5px 0;"><strong>'. t('Your search yielded no results') .'</strong>'. $live_placeholder_text .'</div></div>',
  );

  // include live preview script to show HTML as you type it
  drupal_add_js(drupal_get_path('module', 'annihilatesmurfs') .'/annihilatesmurfs.js', $type = 'module', $scope = 'footer');

  return system_settings_form($form);
}


/**
 * Implementation of hook_menu().
 * Add link to settings page
 */
function annihilatesmurfs_menu() {

  $items = array();

  $items['admin/settings/annihilatesmurfs'] = array(
    'title' => 'Annihilate smurfs',
    'description' => 'Replace the "blue smurf" text with whatever you like',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('annihilatesmurfs_admin'),
    'access arguments' => array('administer annihilatesmurfs'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Validate user input.
 */
function annihilatesmurfs_admin_validate($form, &$form_state) {
  // trim spaces
  $form_state['values']['annihilatesmurfs_term1'] = trim($form_state['values']['annihilatesmurfs_term1']);
  $form_state['values']['annihilatesmurfs_term2'] = trim($form_state['values']['annihilatesmurfs_term2']);
}

